const routes = [
    "/main",
    "/login",
    "/forgot-password",
    "/gtrs/main",
    "/no-access",
    "/gtrs/dashboard",
    "/gtrs/consignments",
    "/gtrs/consignment-details",
    "/gtrs/kpi",
    "/gtrs/kpi/transit-days",
    "/gtrs/add-transit",
    "/gtrs/incident",
    "/gtrs/kpi/holidays",
    "/gtrs/performance",
    "/gtrs/failed-consignments",
    "/gtrs/transport",
    "/gtrs/rdd",
    "/gtrs/missing-pod",
    "/gtrs/safety",
    "/gtrs/no-delivery",
    "/gtrs/additional-charges",
    "/gtrs/driver-login",
    "/gtrs/pack-report",
    "/gtrs/traffic-report",
    "/gtrs/consignment-map",
    "/gtrs/consignment-tracking",
    // "/gtrs/consignment-tracking-2",
    "/gtrs/delivery-report",
    "/gtrs/delivery-report/comments",
    "/gtrs/real-food-report",
]

export default routes
