import {
    ChartPieIcon,
    TruckIcon,
    ClipboardDocumentCheckIcon,
    PresentationChartLineIcon,
    ExclamationTriangleIcon,
    NoSymbolIcon,
    CurrencyDollarIcon,
    UserIcon,
    CircleStackIcon,
    ClockIcon,
    ChevronDownIcon,
    ShieldCheckIcon,
    CameraIcon,
    DocumentTextIcon,
    ClipboardDocumentIcon,
} from "@heroicons/react/24/solid";
import TaskIcon from "@mui/icons-material/Task";
import ReportIcon from "@mui/icons-material/Report";
import { MapPinIcon } from "@heroicons/react/20/solid";

const menu = [
    {
        id: 0,
        name: "Dashboard",
        href: "#",
        icon: ChartPieIcon,
        current: true,
        feature: "Dashboard_view",
        url: "/gtrs/dashboard",
    },
    {
        id: 1,
        name: "Consignments",
        href: "#",
        icon: TruckIcon,
        current: false,
        feature: "ConsignmetsReport_view",
        url: "/gtrs/consignments",
    },
    {
        id: 2,
        name: "KPI Report",
        href: "#",
        icon: ClipboardDocumentCheckIcon,
        current: false,
        options: [
            {
                id: 17,
                name: "KPI",
                href: "#",
                current: false,
                icon: ClipboardDocumentCheckIcon,
                feature: "KPI_view",
                url: "/gtrs/kpi",
            },
            {
                id: 18,
                name: "Transit Days",
                href: "#",
                current: false,
                icon: ClipboardDocumentCheckIcon,
                feature: "View_TransitDays",
                url: "/gtrs/kpi/transit-days",
            },
            {
                id: 13,
                name: "Holidays",
                href: "#",
                current: false,
                icon: ClipboardDocumentCheckIcon,
                feature: "View_Holidays",
                url: "/gtrs/kpi/holidays",
            },
            // {
            //     id: 14,
            //     name: "KPI Reasons",
            //     href: "#",
            //     current: false,
            //     icon: ClipboardDocumentCheckIcon,
            //     feature: "View_KPIReasons",
            //     url: "/gtrs/kpi/reasons",
            // },
        ],
        feature: "KPI_view",
    },
    {
        id: 4,
        name: "Performance Report",
        href: "#",
        icon: PresentationChartLineIcon,
        current: false,
        feature: "Performance_view",
        url: "/gtrs/performance",
    },
    {
        id: 5,
        name: "Failed Consignments",
        href: "#",
        icon: ExclamationTriangleIcon,
        current: false,
        feature: "View_failedConsignment",
        url: "/gtrs/failed-consignments",
    },
    {
        id: 16,
        name: "Transport Report",
        href: "#",
        icon: TaskIcon,
        current: false,
        feature: "View_Transport",
        url: "/gtrs/transport",
    },
    {
        id: 9,
        name: "RDD",
        href: "#",
        icon: ClockIcon,
        current: false,
        feature: "View_RDD",
        url: "/gtrs/rdd",
    },
    {
        id: 11,
        name: "Missing POD",
        href: "#",
        icon: CameraIcon,
        current: false,
        feature: "MissingPOD_view",
        url: "/gtrs/missing-pod",
    },
    {
        id: 10,
        name: "Safety",
        href: "#",
        icon: ShieldCheckIcon,
        current: false,
        feature: "View_safety",
        url: "/gtrs/safety",
    },
    {
        id: 6,
        name: "No Delivery info.",
        href: "#",
        icon: NoSymbolIcon,
        current: false,
        feature: "NoDeliveryInfo_view",
        url: "/gtrs/no-delivery",
    },
    {
        id: 7,
        name: "Additional Charges",
        href: "#",
        icon: CurrencyDollarIcon,
        current: false,
        feature: "AdditionalCharges_view",
        url: "/gtrs/additional-charges",
    },
    {
        id: 8,
        name: "Driver Login",
        href: "#",
        icon: UserIcon,
        current: false,
        feature: "DriverLogin_view",
        url: "/gtrs/driver-login",
    },
    {
        id: 20,
        name: "Unilever KPI Pack",
        href: "#",
        icon: DocumentTextIcon,
        current: false,
        feature: "UnileverReport_View",
        url: "/gtrs/pack-report",
    },
    {
        id: 21,
        name: "Traffic Report",
        href: "#",
        icon: ReportIcon,
        current: false,
        feature: "TrafficReport_View",
        url: "/gtrs/traffic-report",
    },
    {
        id: 23,
        name: "Consignment Tracking",
        href: "#",
        icon: MapPinIcon,
        current: false,
        feature: "ConsignmentTracking_View",
        url: "/gtrs/consignment-tracking",
    },
    {
        id: 25,
        name: "Consignment Tracking 2",
        href: "#",
        icon: ClipboardDocumentIcon,
        current: false,
        feature: "View_Tracking2",
        url: "/gtrs/consignment-tracking-2",
    },
    {
        id: 24,
        name: "Delivery Report",
        href: "#",
        icon: ClipboardDocumentIcon,
        current: false,
        feature: "DeliveryReport_View",
        url: "/gtrs/delivery-report",
    },
    {
        id: 26,
        name: "Real Food KPI Pack",
        href: "#",
        icon: DocumentTextIcon,
        current: false,
        feature: "RealFoodReport_View",
        url: "/gtrs/real-food-report",
    },

];

export default menu;
