import {
    ChartPieIcon,
    TruckIcon,
    ClipboardDocumentCheckIcon,
    PresentationChartLineIcon,
    ExclamationTriangleIcon,
    NoSymbolIcon,
    CurrencyDollarIcon,
    UserIcon, ClockIcon, ShieldCheckIcon,
    CameraIcon,
    DocumentTextIcon,
    ClipboardDocumentIcon,
    RectangleStackIcon
} from "@heroicons/react/24/solid";
import TaskIcon from "@mui/icons-material/Task";
import ReportIcon from "@mui/icons-material/Report";

const menu = [
    {
        id: 0,
        name: "Dashboard",
        href: "#",
        icon: ChartPieIcon,
        current: true,
        feature: "Dashboard_view",
        url: "/testX/dashboard",
    },
    {
        id: 1,
        name: "Consignments",
        href: "#",
        icon: TruckIcon,
        current: false,
        feature: "ConsignmetsReport_view",
        url: "/testX/consignments",
    },
    {
        id: 2,
        name: "KPI Report",
        href: "#",
        icon: ClipboardDocumentCheckIcon,
        current: false,
        options: [
            {
                id: 17,
                name: "KPI",
                href: "#",
                current: false,
                icon: ClipboardDocumentCheckIcon,
                feature: "KPI_view",
                url: "/testX/kpi",
            },
            {
                id: 18,
                name: "Transit Days",
                href: "#",
                current: false,
                icon: ClipboardDocumentCheckIcon,
                feature: "View_TransitDays",
                url: "/testX/kpi/transit-days",
            },
            {
                id: 13,
                name: "Holidays",
                href: "#",
                current: false,
                icon: ClipboardDocumentCheckIcon,
                feature: "View_Holidays",
                url: "/testX/kpi/holidays",
            },
            {
                id: 14,
                name: "KPI Reasons",
                href: "#",
                current: false,
                icon: ClipboardDocumentCheckIcon,
                feature: "View_KPIReasons",
                url: "/testX/kpi/reasons",
            },
        ],
    },
    {
        id: 4,
        name: "Performance Report",
        href: "#",
        icon: PresentationChartLineIcon,
        current: false,
        feature: "Performance_view",
        url: "/testX/performance",
    },
    {
        id: 5,
        name: "Failed Consignments",
        href: "#",
        icon: ExclamationTriangleIcon,
        current: false,
        feature: "View_failedConsignment",
        url: "/testX/failed-consignments",
    },
    {
        id: 9,
        name: "RDD",
        href: "#",
        icon: ClockIcon,
        current: false,
        feature: "View_RDD",
        url: "/testX/rdd",
    },
    {
        id: 11,
        name: "Missing POD",
        href: "#",
        icon: CameraIcon,
        current: false,
        feature: "MissingPOD_view",
        url: "/testX/missing-pod",
    },
    {
        id: 16,
        name: "Transport Report",
        href: "#",
        icon: TaskIcon,
        current: false,
        feature: "View_Transport",
        url: "/testX/transport",
    },
    {
        id: 24,
        name: "Delivery Report",
        href: "#",
        icon: ClipboardDocumentIcon,
        current: false,
        feature: "DeliveryReport_View",
        url: "/testX/delivery-report",
        options: [
            {
                id: 28,
                name: "Delivery Report",
                href: "#",
                current: false,
                icon: ClipboardDocumentCheckIcon,
                feature: "DeliveryReport_View",
                url: "/testX/delivery-report",
            },
            {
                id: 30,
                name: "Excel Delivery Report",
                href: "#",
                current: false,
                icon: ClipboardDocumentCheckIcon,
                feature: "DeliveryReport_View",
                url: "/testX/excel-delivery-report",
            },
            {
                id: 29,
                name: "Delivery Report Comments",
                href: "#",
                current: false,
                icon: ClipboardDocumentCheckIcon,
                feature: "DeliveryReportCommentsTable_View",
                url: "/testX/delivery-report/comments",
            },
        ]
    },
    {
        id: 20,
        name: "Unilever KPI Pack",
        href: "#",
        icon: DocumentTextIcon,
        current: false,
        feature: "UnileverReport_View",
        url: "/testX/pack-report",
    },
    {
        id: 26,
        name: "Real Food KPI Pack",
        href: "#",
        icon: DocumentTextIcon,
        current: false,
        feature: "RealFoodReport_View",
        url: "/testX/real-food-report",
    },
    {
        id: 10,
        name: "Safety",
        href: "#",
        icon: ShieldCheckIcon,
        current: false,
        feature: "View_safety",
        url: "/testX/safety",
    },
    {
        id: 7,
        name: "Additional Charges",
        href: "#",
        icon: CurrencyDollarIcon,
        current: false,
        feature: "AdditionalCharges_view",
        url: "/testX/additional-charges",
    },
    {
        id: 6,
        name: "No Delivery info.",
        href: "#",
        icon: NoSymbolIcon,
        current: false,
        feature: "NoDeliveryInfo_view",
        url: "/testX/no-delivery",
    },
    {
        id: 8,
        name: "Driver Login",
        href: "#",
        icon: UserIcon,
        current: false,
        feature: "DriverLogin_view",
        url: "/testX/driver-login",
    },
    {
        id: 21,
        name: "Traffic Report",
        href: "#",
        icon: ReportIcon,
        current: false,
        feature: "TrafficReport_View",
        url: "/testX/traffic-report",
    },
    // {
    //     id: 23,
    //     name: "Consignment Tracking",
    //     href: "#",
    //     icon: MapPinIcon,
    //     current: false,
    //     feature: "ConsignmentTracking_View",
    //     url: "/testX/consignment-tracking",
    // },
    {
        id: 25,
        name: "Consignment Tracking",
        href: "#",
        icon: ClipboardDocumentIcon,
        current: false,
        feature: "View_Tracking2",
        url: "/testX/consignment-tracking",
    },
    {
        id: 27,
        name: "SOH Report",
        href: "#",
        icon: RectangleStackIcon,
        current: false,
        feature: "StockReport_View",
        url: "/testX/SOH",
    },
];

export default menu;